### ISSUE TITLE
Alphasort lists?

### ISSUE THREAD

**Issue by reedy** [hCaptcha/hcaptcha-integrations-list#14]
Is it possible to add some ordering to the lists? Even if just alphasorting?

When doing #13 it wasn't obvious if I should try and insert it at the bottom, or some other place... As there was no obvious order, unless it was "order added"

**Comment by e271828-** [comment]
@reedy PRs welcome :)

**Comment by reedy** [comment]
I can do a PR if alphasorted is acceptable:)

**Comment by tameryldz** [comment]
nhhjcghj ıufv
