### ISSUE TITLE
Add option "position: absolute" for the captcha widget

### ISSUE THREAD

**Issue by shinebay** [hCaptcha/hcaptcha-integrations-list#17]
the captcha widget position is always fixed to the webpage, please add an option "position: absolute" for the widget
thank you

**Comment by e271828-** [comment]
@shinebay do you mean you'd like it to not scroll with the page?

**Comment by shinebay** [comment]
@e271828- yeah, many users complain that the captcha widget size is too large for small screen(low resolution laptop), they even can't find the "Verify" or "Skip" button to click, since the widget position is always fixed in the screen
adding an option "position: absolute" for the widget can fix this problem

**Comment by e271828-** [comment]
> @e271828- yeah, many users complain that the captcha widget size is too large for small screen(low resolution laptop), they even can't find the "Verify" or "Skip" button to click, since the widget position is always fixed in the screen
> adding an option "position: absolute" for the widget can fix this problem

Any idea what resolution / browser they are using? The widget auto-scales based on this, so it should in general always be visible.

**Comment by shinebay** [comment]
@e271828- I don't know what resolution or browser they are using, I haven't ask them, in my 1080P screen it shows well, but many users said they choose the right images in hcaptcha but then there is no button they can see to go forward, no "Verify" or "Skip" button

**Comment by JusStocks1201** [comment]
Captcha with shirts keeps resetting after first or second selection...help

**Comment by Nordie1** [comment]
Add option position: absolute

**Comment by Nordie1** [comment]
https://github.com/hCaptcha/hcaptcha-integrations-list/issues/17

**Comment by shinebay** [comment]
@e271828- here is just a feedback from my website:
"No matter how much I scroll, there is no next button!"
please fix this problem

**Comment by psiplank** [comment]
u

**Comment by xian-vy** [comment]
Any workaround for this, submit button is hidden on xs screen[
![Screenshot 2024-10-25 090446](https://github.com/user-attachments/assets/23a2e5bc-99e9-425e-9dd1-b7a0565347fa)
](url)
