### ISSUE TITLE
XenForo 2.2 will come with hCaptcha

### ISSUE THREAD

**Issue by ticktackk** [hCaptcha/hcaptcha-integrations-list#5]
I couldn't find any example on how to set supported platform version in the `README.md` so I'm creating this issue instead.

Source: https://xenforo.com/community/posts/1437264

**Comment by e271828-** [comment]
Cool! Will add it.

**Comment by e271828-** [comment]
Closed by https://github.com/hCaptcha/hcaptcha-integrations-list/commit/d01c6deae3be668ca68989f951200eafd8cb49a4
